### ISSUE TITLE
Transfer repozytorium

### ISSUE THREAD

**Issue by xehivs** [w4k2/replicative-resampling#2]
Zaprosiłem już Pana do organizacji – znajdźmy dystynktywną nazwę dla repozytorium i przetransferujmy je do zasobów Katedry.

**Comment by xehivs** [comment]
Proponuje `replicative-resampling`.

**Comment by KarolWojtachnia** [comment]
NIe posiadam uprawnień do przeniesienia repo do `w4k2`

**Comment by xehivs** [comment]
Nadałem Panu tymczasowo uprawnienia właściciela – please use them wisely.
